### PR TITLE
[PROGRAMMES-6456] Update symfony

### PR DESCRIPTION
**Pull request by benolot**
Ticket: https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6456

Ran `composer update symfony/*` and then fixed the one issue that came up (Couldn't load parameters for the comments module).

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by benolot** [comment]
Test this please

**Comment by benolot** [comment]
Ignore failing tests, these will be fixed when https://github.com/bbc/blogs-frontend/pull/117 is merged in

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Pull request merged**
