### PR TITLE
[No ticket] Remove yarn

### PR DESCRIPTION
**Pull request by benolot**

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by BjornTwachtmann** [comment]
@benolot presumably a lot of the packages will have been updated by removing the old lock file and switching to NPM. That's fine, but do we need to do any checking of the compiled assets?

**Comment by benolot** [comment]
@BjornTwachtmann no yarn still got the packages from NPM as the registry, and installed them in node_modules, packages themselves won't change just what we use to manage them.

**Comment by benolot** [comment]
@Bobkidbob why? What's it do?

**Comment by benolot** [comment]
Merging in as googled what it is, doesn't seem overly important and will discuss offline as to whether we want diff highlighting or not on Tuesday when we're all in the office.

**Pull request merged**
