### PR TITLE
In my ever so humble opinion we should default to production mode, no…

### PR DESCRIPTION
**Pull request by BjornTwachtmann**
…t development mode. I'm sure I will figure out soon why this is wrong.

However, note that debug mode is currently enabled on INT/TEST. Which I don't think we want.

### CODE REVIEW

**Comment by programmes-developers** [comment]
Can one of the admins verify this patch?

**Comment by votemike** [comment]
But then if someone doesn't have APP_ENV set up on their machine, they will start logging to the LIVE systems?
What about when comments are ready? If APP_ENV is missing locally (or anywhere), we'll start commenting on LIVE blogs...

**Comment by BjornTwachtmann** [comment]
non-production systems should not have the credentials for production systems, indeed they generally don't. Symfony up until now has always defaulted to the prod env and I think it's the correct behaviour

**Comment by votemike** [comment]
OK. The code look like it will work. Still not sure if I agree with it.... but fair enough...

**Comment by BjornTwachtmann** [comment]
So the reason I raised this was that the existing code was defaulting to debug mode on in production. I think that's more dangerous than the reverse. It potentially exposes internals or brings down systems.

**Comment by BPScott** [comment]
I reckon a better fix for this would be to explicitly set the APP_DEBUG environment variable to 0 in https://github.com/bbc/blogs-frontend/blob/master/bake-scripts/01-configure-component#L30.

Imo we should try and avoid editing the default symfony frontcontroller.

**Pull request merged**
